dist: xenial

language: python

sudo: false

python:
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install pytest coverage coveralls

script:
  - coverage run --source=pysyge setup.py test

after_success:
  - coveralls
